apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
      - name: alert-manager
        image: 685016229870.dkr.ecr.us-west-2.amazonaws.com/alert-manager:latest
        ports:
        - containerPort: 5000
