apiVersion: v1
kind: Service
metadata:
  name: alert-manager-service
  namespace: observability
spec:
  selector:
    app: alert-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP