    groups:
      - name: demo_alert
        rules:
          - alert: KubePodCrashLooping
            expr: kube_pod_container_status_restarts_total > 5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod is crash looping"
              description: "Pod {{ $labels.pod }} is restarting frequently."